const domains = {
  security: { label: 'DOMAIN 01 · 26% OF EXAM', title: 'Security Principles', intro: 'This is the foundation of the entire CC exam: understand what security is protecting, how risks are handled, and how people and organizations make security decisions.', concepts: [['CIA triad', 'Confidentiality prevents improper disclosure; integrity prevents improper change; availability keeps systems usable.'], ['Risk management', 'Identify a risk, assess likelihood and impact, then avoid, mitigate, transfer, or accept it.'], ['Control families', 'Administrative: policies and training. Technical: MFA and firewalls. Physical: locks and guards.'], ['Governance', 'Policies state what; standards set rules; procedures explain how.']], coach: 'You already know hashing supports integrity. Now connect it to the full CIA triad.', questions: [
    ['Which security objective ensures information is accurate and has not been improperly altered?', ['Availability', 'Integrity', 'Confidentiality', 'Privacy'], 1, 'Integrity protects data from unauthorized or accidental modification.'],
    ['A company buys cyber insurance to reduce the financial impact of a breach. Which risk treatment is this?', ['Avoidance', 'Acceptance', 'Transfer', 'Mitigation'], 2, 'Insurance shifts some financial consequences to another party: risk transfer.'],
    ['Which is an administrative security control?', ['A firewall', 'Employee security-awareness training', 'A smart-card reader', 'Disk encryption'], 1, 'Training is an administrative control; the others are technical or physical controls.'],
    ['A policy says passwords must be changed every 90 days. A detailed document tells staff the exact steps to change one. That document is a:', ['Standard', 'Procedure', 'Regulation', 'Risk assessment'], 1, 'A procedure gives step-by-step instructions for carrying out a policy.'],
    ['Which control is designed to discourage an attacker before an incident occurs?', ['Corrective', 'Detective', 'Deterrent', 'Recovery'], 2, 'Deterrent controls discourage unwanted actions, such as warning signs or visible cameras.'] ] },
  bcdr: { label: 'DOMAIN 02 · 10% OF EXAM', title: 'BC, DR & Incident Response', intro: 'Learn how an organization continues critical work, restores technology after disruption, and responds methodically to security incidents.', concepts: [['Business continuity', 'Keeps essential business functions operating during a disruption.'], ['Disaster recovery', 'Restores systems, infrastructure, and data after a disaster.'], ['RTO & RPO', 'RTO is acceptable downtime. RPO is acceptable data loss, measured in time.'], ['Incident response', 'Prepare → detect/analyze → contain → eradicate → recover → learn.']], coach: 'You got RPO right. Next, make RTO and RPO feel automatic.', questions: [['A maximum of two hours of acceptable system downtime is the:', ['RPO', 'RTO', 'BIA', 'SLA'], 1, 'RTO is the recovery time objective: how quickly a service must be restored.']] },
  access: { label: 'DOMAIN 03 · 22% OF EXAM', title: 'Access Controls', intro: 'Control who can enter physical spaces and use digital systems—and only grant the access they truly need.', concepts: [['Least privilege', 'Give only the minimum access necessary to do the job.'], ['Segregation of duties', 'Split sensitive tasks so one person cannot complete a risky process alone.'], ['Access models', 'DAC is owner-controlled; MAC is label/clearance based; RBAC follows job roles.'], ['Authentication', 'Prove identity with something you know, have, are, or do. MFA uses more than one factor.']], coach: 'RBAC is already in your toolkit. Compare it closely with MAC and DAC.', questions: [['Which model assigns permissions based on a person’s job function?', ['MAC', 'DAC', 'RBAC', 'ABAC'], 2, 'Role-based access control maps permissions to job roles.']] },
  network: { label: 'DOMAIN 04 · 24% OF EXAM', title: 'Network Security', intro: 'Understand how systems communicate, where common services run, and how networks are protected from misuse.', concepts: [['Network models', 'OSI has seven layers; TCP/IP is the practical Internet model.'], ['Common ports', 'Know 22 SSH, 53 DNS, 80 HTTP, 443 HTTPS, 25 SMTP, and 3389 RDP.'], ['Segmentation', 'Separate networks to limit access and contain an incident.'], ['Protective tools', 'Firewalls filter traffic; IDS detects suspicious activity; IPS can block it.']], coach: 'Focus on the reason behind each protocol—not just the port number.', questions: [['Which port is normally used by HTTPS?', ['22', '53', '80', '443'], 3, 'HTTPS normally uses TCP port 443.']] },
  operations: { label: 'DOMAIN 05 · 18% OF EXAM', title: 'Security Operations', intro: 'Protect data in daily work: handle it carefully, harden systems, monitor events, and follow sound policies.', concepts: [['Encryption & hashing', 'Encryption protects confidentiality; hashing is one-way and helps verify integrity.'], ['Data handling', 'Classify, label, retain, and securely destroy data according to its sensitivity.'], ['Hardening', 'Use secure baselines, timely patches, minimal services, and configuration management.'], ['Logging', 'Logs and monitoring help detect, investigate, and respond to suspicious events.']], coach: 'Your hashing answer was right. Learn when encryption—not hashing—is the answer.', questions: [['Which technique is one-way and is commonly used to verify data integrity?', ['Symmetric encryption', 'Hashing', 'Tokenization', 'Asymmetric encryption'], 1, 'A hash is a fixed-length, one-way value used to check integrity.']] }
};
const playlist = {
  security: [['Domain 1 practice questions', '19 min', '0F3QP2Bt1KI'], ['Threats, risks & vulnerabilities', '20 min', 'KJ6tydGo-zc']],
  bcdr: [['Domain 2 practice questions', '29 min', 'lSkjmlb2cQ4']],
  access: [['Domain 3 practice questions', '22 min', 'qD_qFoJ4XHg']],
  network: [['Domain 4 practice questions', '19 min', 'uMCWc3tmmf4'], ['Attack surface', '13 min', 'fr9susGp3Vk']],
  operations: [['Domain 5 practice questions', '27 min', 'YP2U6Tiuf1A'], ['PKI for beginners', '22 min', 'SQlJcWqyqqI'], ['Phishing types & safety', '15 min', 'b_DrAudSo38']]
};
const add = (key, qs) => domains[key].questions.push(...qs);
add('security', [['A low-impact risk is monitored without further spending. This is:', ['Transfer','Acceptance','Avoidance','Mitigation'], 1, 'Choosing to live with an assessed risk is acceptance.', 'Exam'], ['Permissions were not reviewed after an employee changed role. What most directly prevents a repeat?', ['Periodic access review','A backup','CCTV','A postmortem'], 0, 'Access reviews catch access that no longer matches a job.', 'Challenge']]);
add('bcdr', [['A service must be restored in four hours and lose no more than 30 minutes of data. Which is correct?', ['RTO 30 min; RPO 4 hr','RTO 4 hr; RPO 30 min','RTO 4 hr; RPO 4 hr','RTO 30 min; RPO 30 min'], 1, 'RTO is restoration time; RPO is acceptable data loss.', 'Exam'], ['Before restoring ransomware-hit systems to production, first:', ['Eradicate the cause and validate clean backups','Publish a press release','Accept the risk','Update job roles'], 0, 'Restoring before containment can reintroduce the incident.', 'Challenge']]);
add('access', [['Clearances and document classifications determine access. This is:', ['DAC','RBAC','MAC','Least privilege'], 2, 'MAC uses centrally enforced labels and clearances.', 'Exam'], ['A clerk creates suppliers but cannot approve payments to them. This is:', ['Job rotation','Separation of duties','Single sign-on','Need to know'], 1, 'Splitting sensitive work reduces fraud and error.', 'Challenge']]);
add('network', [['Which device can detect suspicious traffic and automatically block it?', ['Hub','IDS','IPS','Proxy'], 2, 'An IPS is inline and can block; an IDS mainly alerts.', 'Exam'], ['A web server is isolated from internal databases to limit compromise impact. This uses:', ['Network segmentation','Data retention','Hashing','Single sign-on'], 0, 'Segmentation reduces lateral movement and blast radius.', 'Challenge']]);
add('operations', [['Which PKI component binds a public key to an identity?', ['Certificate','Hash','Firewall rule','Backup'], 0, 'A certificate contains identity and a public key, signed by a trusted authority.', 'Exam'], ['A payroll worker gets an urgent look-alike password-reset email. The best immediate action is to:', ['Use its link privately','Verify independently and report it','Forward it widely','Reply with credentials'], 1, 'Do not use embedded links; independently verify suspicious requests.', 'Challenge']]);
const state = JSON.parse(localStorage.getItem('ccStudyCoach') || '{"completed":[],"notes":"","answered":0,"correct":0,"difficulty":"Foundation"}');
let selectedDomain = 'security', questionIndex = 0, answered = false;
const $ = id => document.getElementById(id);
function save(){localStorage.setItem('ccStudyCoach',JSON.stringify(state));}
function daysToExam(){const now=new Date();const year=now.getFullYear();let exam=new Date(year,8,30);if(exam<now)exam=new Date(year+1,8,30);return Math.ceil((exam-now)/86400000);}
function updateProgress(){const completed=state.completed.length;$('courseProgress').style.width=`${completed*20}%`;$('progressText').textContent=`${completed} of 5 domains completed`;}
function renderDomain(key){selectedDomain=key;questionIndex=0;answered=false;const d=domains[key];document.querySelectorAll('.domain-tab').forEach(x=>x.classList.toggle('active',x.dataset.domain===key));$('domainLabel').textContent=d.label;$('lessonTitle').textContent=d.title;$('lessonIntro').textContent=d.intro;$('concepts').innerHTML=d.concepts.map(c=>`<div class="concept"><h3>${c[0]}</h3><p>${c[1]}</p></div>`).join('');$('playlistItems').innerHTML=playlist[key].map(v=>`<a class="playlist-item" href="https://www.youtube.com/watch?v=${v[2]}&list=PL0hT6hgexlYw-k6GxQf_DIAPdc96T2MP-" target="_blank" rel="noopener"><span>${v[0]}</span><small>${v[1]} ↗</small></a>`).join('');const complete=state.completed.includes(key);$('statusPill').textContent=complete?'COMPLETE':'IN PROGRESS';$('statusPill').classList.toggle('done',complete);$('markComplete').textContent=complete?'Completed ✓':'Mark this domain complete →';$('coachMessage').textContent=d.coach;$('coachTitle').textContent=complete?'Nicely done':'A strong start';renderQuestion();}
function renderQuestion(){const level=state.difficulty||'Foundation';const qs=domains[selectedDomain].questions.filter(q=>(q[4]||'Foundation')===level);const q=qs[questionIndex%qs.length];answered=false;$('quizProgress').textContent=`${level} · Question ${questionIndex+1} of ${qs.length}`;$('questionTag').textContent=`${domains[selectedDomain].title.toUpperCase()} · ${level.toUpperCase()}`;$('questionText').textContent=q[0];$('answers').innerHTML=q[1].map((a,i)=>`<button class="answer" data-answer="${i}">${String.fromCharCode(65+i)}. ${a}</button>`).join('');$('feedback').innerHTML='';$('nextQuestion').hidden=true;document.querySelectorAll('.answer').forEach(b=>b.addEventListener('click',()=>checkAnswer(+b.dataset.answer,q)));}
function checkAnswer(choice,q){if(answered)return;answered=true;state.answered++;const right=choice===q[2];if(right)state.correct++;save();document.querySelectorAll('.answer').forEach(b=>{b.disabled=true;const index=+b.dataset.answer;if(index===q[2])b.classList.add('correct');else if(index===choice)b.classList.add('wrong');});$('feedback').innerHTML=right?`<strong>Correct.</strong> ${q[3]}`:`<strong>Not quite.</strong> ${q[3]}`;$('nextQuestion').hidden=false;}
document.querySelectorAll('.domain-tab').forEach(b=>b.addEventListener('click',()=>renderDomain(b.dataset.domain)));
$('markComplete').addEventListener('click',()=>{if(!state.completed.includes(selectedDomain))state.completed.push(selectedDomain);else state.completed=state.completed.filter(x=>x!==selectedDomain);save();updateProgress();renderDomain(selectedDomain);});
$('nextQuestion').addEventListener('click',()=>{questionIndex++;renderQuestion();});
$('difficulty').value=state.difficulty||'Foundation';$('difficulty').addEventListener('change',e=>{state.difficulty=e.target.value;questionIndex=0;save();renderQuestion();});
$('notes').value=state.notes||'';$('saveNotes').addEventListener('click',()=>{state.notes=$('notes').value;save();$('saveMessage').textContent='Saved on this device.';setTimeout(()=>$('saveMessage').textContent='',2200);});
$('daysLeft').textContent=daysToExam();$('streakCount').textContent=state.answered ? '1 day' : 'Start today';updateProgress();renderDomain(selectedDomain);
